// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using be.Data;

#nullable disable

namespace be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("be.Models.Bendahara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bendaharas");
                });

            modelBuilder.Entity("be.Models.ExclusionIuranSiswa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alasan")
                        .HasColumnType("text");

                    b.Property<Guid>("IuranKhususId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SiswaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TanggalDikecualikan")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SiswaId");

                    b.HasIndex("IuranKhususId", "SiswaId")
                        .IsUnique();

                    b.ToTable("ExclusionIuranSiswas");
                });

            modelBuilder.Entity("be.Models.HariLibur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCustomOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HariLiburs");
                });

            modelBuilder.Entity("be.Models.IuranKhusus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("JudulIuran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalDibuat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TargetNominalPerSiswa")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("IuranKhususs");
                });

            modelBuilder.Entity("be.Models.PembayaranIuranKhusus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLunas")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IuranKhususId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SiswaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TanggalBayar")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalTerbayar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SiswaId");

                    b.HasIndex("IuranKhususId", "SiswaId")
                        .IsUnique();

                    b.ToTable("PembayaranIuranKhususs");
                });

            modelBuilder.Entity("be.Models.PengaturanKas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("NominalKas")
                        .HasColumnType("numeric");

                    b.Property<string>("TipeJadwal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PengaturanKas");
                });

            modelBuilder.Entity("be.Models.Siswa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NoAbsen")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Siswas");
                });

            modelBuilder.Entity("be.Models.TransaksiKas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BulanPeriode")
                        .HasColumnType("text");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MingguKe")
                        .HasColumnType("integer");

                    b.Property<decimal>("Nominal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SiswaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TanggalBayar")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TanggalBayarSpec")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiswaId");

                    b.ToTable("TransaksiKas");
                });

            modelBuilder.Entity("be.Models.TransaksiLain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuktiFoto")
                        .HasColumnType("text");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<decimal>("Nominal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransaksiLains");
                });

            modelBuilder.Entity("be.Models.ExclusionIuranSiswa", b =>
                {
                    b.HasOne("be.Models.IuranKhusus", "IuranKhusus")
                        .WithMany()
                        .HasForeignKey("IuranKhususId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("be.Models.Siswa", "Siswa")
                        .WithMany()
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IuranKhusus");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("be.Models.PembayaranIuranKhusus", b =>
                {
                    b.HasOne("be.Models.IuranKhusus", "IuranKhusus")
                        .WithMany()
                        .HasForeignKey("IuranKhususId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("be.Models.Siswa", "Siswa")
                        .WithMany()
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IuranKhusus");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("be.Models.TransaksiKas", b =>
                {
                    b.HasOne("be.Models.Siswa", "Siswa")
                        .WithMany()
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siswa");
                });
#pragma warning restore 612, 618
        }
    }
}
